= Eindopdracht NOVI Frontend
:toc: macro

|======
| Instelling    | NOVI HBO Software Development
| Leerlijn      | FrontEnd 2021/03
| Document      | Verantwoording voor de Eindopdracht
| Docent        | Nova Eeken / Rein op 't Land
| Datum         | 18 juli 2021
| Auteur        | Jurjen Vorhauer
| Email         | J.Vorhauer@novi-education.nl
| Studentnummer | 800009793
| GitHub        | https://github.com/jvorhauer/novi-frontend-eindopdracht
| *Noviaal*     | Een Twitterig platform, de naam is een samentrekking van NOVI en Sociaal
|======

<<<

toc::[]

<<<

Dit is het Verwantwoordingsdocument voor de eindopdracht van de NOVI HBO Software Development Frontend module.

In dit document legt de auteur van de implementatie van de eindopdracht verantwoording af voor functionele en technische keuzes. Het betreft keuzes die invloed hebben op

1. de functionaliteit die de eindopdracht-applicatie biedt t.o.v. de beloofde functionaliteit in de het F.O.
2. de technische keuzes die nodig waren om het geheel correct aan de gang te krijgen.

== Functionele keuzes

=== Tags

De beloofde `tags` zitten niet in de applicatie. De reden is dat deze extra functionaliteit niet veel toevoegd aan de rest van de applicatie. Om tijd en energie te sparen heb ik er voor gekozen om dit deel helemaal over te slaan.

== Technische keuzes

=== Backend

De backend is het resultaat van de eindopdracht voor de leerlijn 'Backend' van NOVI. Deze Java + Spring applicatie biedt een REST API voor het beheren van notities.

==== hosting

Een optie is natuurlijk om de backend mee te leveren en dan maar te hopen dat zowel backend als frontend (deze eindopdracht applicatie) goed draaien.

In plaats van extra inspanning te vragen van de examinatoren, heb ik gekozen om de backend op Heroku te hosten.

==== fixes

Ondanks een, voor mijn gevoel, erg vleiend cijfer voor die backend eindopdracht applicatie, bleken er een paar bugs in te zitten, die inmiddels gefixed zijn. Dat wil dus wel zeggen dat de nu via Heroku beschikbare backend niet dezelfde is als de ingeleverde applicatie toendertijd.
